name: OwlMail Github Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create Secret files
        run: cat /home/runner/work/OwlMail/OwlMail/app/google-services.json | base64

      - name: Update Secrets data
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $DATA > /home/runner/work/OwlMail/OwlMail/app/google-services.json

      - name: Clean project
        run: ./gradlew clean

#      - name: Stopping gradle
#        run: ./gradlew --stop

      - name: Lint Check
        run: ./gradlew lintDebug

      - name: Generate Debug Bundle
        run: ./gradlew bundleDebug

#      - name: Post build project clean up
#       run: ./gradlew clean
