name: OwlMail Detekt

on:
  push:
    branches:
      - "detekt*"
jobs:
  detekt:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Fetch Secrets data
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $DATA > $PWD/app/google-services.json

      - name: Detekt Check
        run: ./gradlew detekt --scan

      - uses: actions/upload-artifact@v3
        with:
          name: Detekt-Report
          path: app/build/reports/detekt