name: OwlMail Apk

on:
  push:
    branches:
      - "*"
      - "!profiler*"
#      - "main"
#  pull_request:
#    branches:
#      - "*"
#      - "!profiler*"
jobs:
  generate-apk:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Gradle with Cache
        uses: gradle/gradle-build-action@v2

      - name: Fetch Secrets data
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $DATA > $PWD/app/google-services.json

      - name: Generate Release Apk
        run: ./gradlew assembleRelease --scan

      - uses: actions/upload-artifact@v3
        with:
          name: Release Apk
          path: app/build/outputs/apk/release/app-release.apk